/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.7.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    java
    id("com.github.johnrengelman.shadow") version "6.1.0"
}

java {
    sourceCompatibility = JavaVersion.VERSION_14
}

tasks.withType<JavaCompile> {
    // Java records are a preview feature in Java 14 (compile)
    options.compilerArgs.add("--enable-preview")
}

tasks.test {
    useJUnitPlatform()
    // Java records are a preview feature in Java 14 (test)
    jvmArgs("--enable-preview")
}

repositories {
    // Use JCenter for resolving dependencies.
    jcenter()
}

dependencies {
    // Use JUnit Jupiter API for testing.
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.6.2")

    // Use JUnit Jupiter Engine for testing.
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")

    // This dependency is used by the application.
    implementation("org.fusesource.jansi:jansi:2.0.1")
}

application {
    // Define the main class for the application.
    getMainClass().set("com.selesy.nqueens.App") // Required in Gradle 8.0
    mainClassName = getMainClass().get() // TODO: deprecated but currently required for shadow
    // Java records are a preview feature in Java 14 (execution)
    applicationDefaultJvmArgs = listOf("--enable-preview","-Dspring.output.ansi.enabled=always")
}

tasks.test {
    // Use junit platform for unit tests.
    useJUnitPlatform()
}

// task runApp(type: JavaExec) {
//     standardInput = System.in
//     standardOutput = System.out
// }

// 
// shadow {
//     mainClassName = "com.selesy.nqueens.App"
//     // mainClassName.set("com.selesy.nqueens.App")
// }

// shadowJar {
//     manifest {
//         attributes 'Main-Class': mainClassName
//     }
// }

// tasks.withType<ShadowJar> {
//     manifest {
//         attributes(mapOf(
//                 "Main-Class" to "test.ApplicationKt"
//         ))
//     }
// }

// tasks.withType<Jar> {
//     manifest {
//         // mainClassName("com.selesy.nqueens.App")
//         attributes["Main-Class"] = "com.selesy.nqueens.App"
//     }
// }

// tasks.withType<ShadowJar> {
//     mainClassName(application.mainClass)
// }
