/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.7.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    java
    // Allows classpath generation (from dependencies) for Eclipse and VS Code
    eclipse
    // Boiler-plate generation
    id("io.freefair.lombok") version "5.3.0"
    // Creates a jar with dependencies (uber/shade/etc)
    id("com.github.johnrengelman.shadow") version "6.1.0"
}

java {
    sourceCompatibility = JavaVersion.VERSION_14
}

tasks.test {
    useJUnitPlatform()
}

repositories {
    // Use JCenter for resolving dependencies.
    jcenter()
}

dependencies {
    // Use JUnit Jupiter API for testing.
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.6.2")

    // Use JUnit Jupiter Engine for testing.
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")

    // These dependencies is used by the application.
    implementation("org.projectlombok:lombok:1.18.16")
    implementation("org.fusesource.jansi:jansi:2.0.1")
}

application {
    // Define the main class for the application.
    getMainClass().set("com.selesy.nqueens.App") // Required in Gradle 8.0
    mainClassName = "com.selesy.nqueens.App" // Deprecated in Gradle but required for Shadow
}
